
package jysc.webservice.pmsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WctWebServiceI", targetNamespace = "http://impl.server.webservice.data.tzsc.shlanbao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WctWebServiceI {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WCTSendEqpRealTimeData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WCTSendEqpRealTimeData", targetNamespace = "http://impl.server.webservice.data.tzsc.shlanbao.com/", className = "jysc.webservice.pmsClient.WCTSendEqpRealTimeData")
    @ResponseWrapper(localName = "WCTSendEqpRealTimeDataResponse", targetNamespace = "http://impl.server.webservice.data.tzsc.shlanbao.com/", className = "jysc.webservice.pmsClient.WCTSendEqpRealTimeDataResponse")
    public String wctSendEqpRealTimeData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WCTSendOrderStatusChanges")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WCTSendOrderStatusChanges", targetNamespace = "http://impl.server.webservice.data.tzsc.shlanbao.com/", className = "jysc.webservice.pmsClient.WCTSendOrderStatusChanges")
    @ResponseWrapper(localName = "WCTSendOrderStatusChangesResponse", targetNamespace = "http://impl.server.webservice.data.tzsc.shlanbao.com/", className = "jysc.webservice.pmsClient.WCTSendOrderStatusChangesResponse")
    public String wctSendOrderStatusChanges(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
