
package jysc.webservice.pmsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WctWebServiceIpmlService", targetNamespace = "http://impl.server.webservice.data.tzsc.shlanbao.com/", wsdlLocation = "http://localhost:8090/jysc/ws//pmsWebService?wsdl")
public class WctWebServiceIpmlService
    extends Service
{

    private final static URL WCTWEBSERVICEIPMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WCTWEBSERVICEIPMLSERVICE_EXCEPTION;
    private final static QName WCTWEBSERVICEIPMLSERVICE_QNAME = new QName("http://impl.server.webservice.data.tzsc.shlanbao.com/", "WctWebServiceIpmlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/jysc/ws//pmsWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WCTWEBSERVICEIPMLSERVICE_WSDL_LOCATION = url;
        WCTWEBSERVICEIPMLSERVICE_EXCEPTION = e;
    }

    public WctWebServiceIpmlService() {
        super(__getWsdlLocation(), WCTWEBSERVICEIPMLSERVICE_QNAME);
    }

    public WctWebServiceIpmlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WCTWEBSERVICEIPMLSERVICE_QNAME, features);
    }

    public WctWebServiceIpmlService(URL wsdlLocation) {
        super(wsdlLocation, WCTWEBSERVICEIPMLSERVICE_QNAME);
    }

    public WctWebServiceIpmlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WCTWEBSERVICEIPMLSERVICE_QNAME, features);
    }

    public WctWebServiceIpmlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WctWebServiceIpmlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WctWebServiceI
     */
    @WebEndpoint(name = "WctWebServiceIpmlPort")
    public WctWebServiceI getWctWebServiceIpmlPort() {
        return super.getPort(new QName("http://impl.server.webservice.data.tzsc.shlanbao.com/", "WctWebServiceIpmlPort"), WctWebServiceI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WctWebServiceI
     */
    @WebEndpoint(name = "WctWebServiceIpmlPort")
    public WctWebServiceI getWctWebServiceIpmlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.server.webservice.data.tzsc.shlanbao.com/", "WctWebServiceIpmlPort"), WctWebServiceI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WCTWEBSERVICEIPMLSERVICE_EXCEPTION!= null) {
            throw WCTWEBSERVICEIPMLSERVICE_EXCEPTION;
        }
        return WCTWEBSERVICEIPMLSERVICE_WSDL_LOCATION;
    }

}
