package com.shlanbao.tzsc.base.mapping;

// Generated 2013-12-26 14:09:00 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * MdManualShift generated by hbm2java
 */
@SuppressWarnings("serial")
public class MdManualShift implements java.io.Serializable {
	private int id;			//主键
	private String eqpid;		//设备code
	private Date shifttime;//换班时间
	private int dasprocess;	//WCT换班状态0:工单结束，1.表示DAC更新的状态 2.表示PMS系统更新的状态
	private int pmsprocess; //PMS换班状态0:工单结束，1.表示DAC更新的状态 2.表示PMS系统更新的状态
	private String note;	//备注
	private String workShop;//1.1号车间，2号车间
	private String teamCode;//班组
	private String shiftCode;//班次
	private String addUserId;	//新增人
	private Date addTime;		//新增时间
	private String modifyUserId;//修改人
	private Date modifyTime;//修改时间
	private String proWorkId;//工单主键ID
	private String state;//工单运行状态
	private String pmvStartMsg;//工单开始的值
	private String pmvMsg;	//早班上一班工单结束的PLC值
	private String pmv1Msg;	//中班托班时PLC自动换班的值
	private String pmv2Msg; //晚班托班时PLC自动换班的值
	
	private String pmvStartTime; 
	private String pmvTime;
	private String pmv1Time; 
	private String pmv2Time; 
	private String workType;//机台型号
	
	private String pmvStartFlMsg;//工单开始的辅料值
	private String pmvFlMsg;//早班上一班工单结束的PLC辅料值
	private String pmv1FlMsg;//中班托班时PLC自动换班的辅料值
	private String pmv2FlMsg;//晚班托班时PLC自动换班的辅料值

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getEqpid() {
		return eqpid;
	}
	public void setEqpid(String eqpid) {
		this.eqpid = eqpid;
	}
	public Date getShifttime() {
		return shifttime;
	}
	public void setShifttime(Date shifttime) {
		this.shifttime = shifttime;
	}
	public int getDasprocess() {
		return dasprocess;
	}
	public void setDasprocess(int dasprocess) {
		this.dasprocess = dasprocess;
	}
	public int getPmsprocess() {
		return pmsprocess;
	}
	public void setPmsprocess(int pmsprocess) {
		this.pmsprocess = pmsprocess;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public String getWorkShop() {
		return workShop;
	}
	public void setWorkShop(String workShop) {
		this.workShop = workShop;
	}
	public String getAddUserId() {
		return addUserId;
	}
	public void setAddUserId(String addUserId) {
		this.addUserId = addUserId;
	}
	public Date getAddTime() {
		return addTime;
	}
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}
	public String getModifyUserId() {
		return modifyUserId;
	}
	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}
	public Date getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	public String getProWorkId() {
		return proWorkId;
	}
	public void setProWorkId(String proWorkId) {
		this.proWorkId = proWorkId;
	}
	public String getPmvMsg() {
		return pmvMsg;
	}
	public void setPmvMsg(String pmvMsg) {
		this.pmvMsg = pmvMsg;
	}
	public String getPmv1Msg() {
		return pmv1Msg;
	}
	public void setPmv1Msg(String pmv1Msg) {
		this.pmv1Msg = pmv1Msg;
	}
	public String getPmv2Msg() {
		return pmv2Msg;
	}
	public void setPmv2Msg(String pmv2Msg) {
		this.pmv2Msg = pmv2Msg;
	}
	public String getTeamCode() {
		return teamCode;
	}
	public void setTeamCode(String teamCode) {
		this.teamCode = teamCode;
	}
	public String getShiftCode() {
		return shiftCode;
	}
	public void setShiftCode(String shiftCode) {
		this.shiftCode = shiftCode;
	}
	public String getPmvStartMsg() {
		return pmvStartMsg;
	}
	public void setPmvStartMsg(String pmvStartMsg) {
		this.pmvStartMsg = pmvStartMsg;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getPmvStartTime() {
		return pmvStartTime;
	}
	public void setPmvStartTime(String pmvStartTime) {
		this.pmvStartTime = pmvStartTime;
	}
	public String getPmvTime() {
		return pmvTime;
	}
	public void setPmvTime(String pmvTime) {
		this.pmvTime = pmvTime;
	}
	public String getPmv1Time() {
		return pmv1Time;
	}
	public void setPmv1Time(String pmv1Time) {
		this.pmv1Time = pmv1Time;
	}
	public String getPmv2Time() {
		return pmv2Time;
	}
	public void setPmv2Time(String pmv2Time) {
		this.pmv2Time = pmv2Time;
	}
	public String getWorkType() {
		return workType;
	}
	public void setWorkType(String workType) {
		this.workType = workType;
	}
	public String getPmvStartFlMsg() {
		return pmvStartFlMsg;
	}
	public void setPmvStartFlMsg(String pmvStartFlMsg) {
		this.pmvStartFlMsg = pmvStartFlMsg;
	}
	public String getPmvFlMsg() {
		return pmvFlMsg;
	}
	public void setPmvFlMsg(String pmvFlMsg) {
		this.pmvFlMsg = pmvFlMsg;
	}
	public String getPmv1FlMsg() {
		return pmv1FlMsg;
	}
	public void setPmv1FlMsg(String pmv1FlMsg) {
		this.pmv1FlMsg = pmv1FlMsg;
	}
	public String getPmv2FlMsg() {
		return pmv2FlMsg;
	}
	public void setPmv2FlMsg(String pmv2FlMsg) {
		this.pmv2FlMsg = pmv2FlMsg;
	}
}
