package com.shlanbao.tzsc.base.mapping;

// Generated 2013-12-26 14:09:00 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * MdManualShiftLog generated by hbm2java
 */
@SuppressWarnings("serial")
public class MdManualShiftLog implements java.io.Serializable {
	private int id;			//主键
	private String eqpid;		//设备code
	private Date shifttime;//换班时间
	private int dasprocess;	//WCT换班状态0:工单结束，1.表示DAC更新的状态 2.表示PMS系统更新的状态
	private int pmsprocess; //PMS换班状态0:工单结束，1.表示DAC更新的状态 2.表示PMS系统更新的状态
	private String note;	//备注
	private String workShop;//1.1号车间，2号车间
	private String addUserId;	//新增人
	private Date addTime;		//新增时间
	private String modifyUserId;//修改人
	private Date modifyTime;//修改时间
	private String proWorkId;//工单主键ID
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getEqpid() {
		return eqpid;
	}
	public void setEqpid(String eqpid) {
		this.eqpid = eqpid;
	}
	public Date getShifttime() {
		return shifttime;
	}
	public void setShifttime(Date shifttime) {
		this.shifttime = shifttime;
	}
	public int getDasprocess() {
		return dasprocess;
	}
	public void setDasprocess(int dasprocess) {
		this.dasprocess = dasprocess;
	}
	public int getPmsprocess() {
		return pmsprocess;
	}
	public void setPmsprocess(int pmsprocess) {
		this.pmsprocess = pmsprocess;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public String getWorkShop() {
		return workShop;
	}
	public void setWorkShop(String workShop) {
		this.workShop = workShop;
	}
	public String getAddUserId() {
		return addUserId;
	}
	public void setAddUserId(String addUserId) {
		this.addUserId = addUserId;
	}
	public Date getAddTime() {
		return addTime;
	}
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}
	public String getModifyUserId() {
		return modifyUserId;
	}
	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}
	public Date getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	public String getProWorkId() {
		return proWorkId;
	}
	public void setProWorkId(String proWorkId) {
		this.proWorkId = proWorkId;
	}
	

}
