package org.tspm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-11-24T19:29:42.311+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "REC_DAS_ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RECDASServiceSoap {

    /**
     * 卷包数采数据接收服务
     */
    @WebResult(name = "ExecuteXML_DASResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteXML_DAS", targetNamespace = "http://tempuri.org/", className = "org.tspm.ExecuteXMLDAS")
    @WebMethod(operationName = "ExecuteXML_DAS", action = "http://tempuri.org/ExecuteXML_DAS")
    @ResponseWrapper(localName = "ExecuteXML_DASResponse", targetNamespace = "http://tempuri.org/", className = "org.tspm.ExecuteXMLDASResponse")
    public org.tspm.ArrayOfString executeXMLDAS(
        @WebParam(name = "strXML", targetNamespace = "http://tempuri.org/")
        java.lang.String strXML
    );
}
