
package org.tspm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-11-24T19:29:42.229+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class RECDASServiceSoap_RECDASServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "REC_DAS_Service");

    private RECDASServiceSoap_RECDASServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RECDASService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RECDASService ss = new RECDASService(wsdlURL, SERVICE_NAME);
        RECDASServiceSoap port = ss.getRECDASServiceSoap12();  
        
        {
        System.out.println("Invoking executeXMLDAS...");
        java.lang.String _executeXMLDAS_strXML = "";
        org.tspm.ArrayOfString _executeXMLDAS__return = port.executeXMLDAS(_executeXMLDAS_strXML);
        System.out.println("executeXMLDAS.result=" + _executeXMLDAS__return);


        }

        System.exit(0);
    }

}
