package org.tspm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-11-24T19:29:42.304+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "REC_DAS_ServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RECDASServiceHttpGet {

    /**
     * 卷包数采数据接收服务
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ExecuteXML_DAS")
    public ArrayOfString executeXMLDAS(
        @WebParam(partName = "strXML", name = "strXML", targetNamespace = "http://tempuri.org/")
        java.lang.String strXML
    );
}
