
package org.tspm;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-11-24T19:29:42.324+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class RECDASServiceHttpGet_RECDASServiceHttpGet_Server{

    protected RECDASServiceHttpGet_RECDASServiceHttpGet_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new REC_DAS_ServiceHttpGetImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new RECDASServiceHttpGet_RECDASServiceHttpGet_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
