package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-28T15:39:48.250+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "WebService1", 
                  wsdlLocation = "http://10.114.81.103:82/WebService1.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class WebService1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "WebService1");
    public final static QName WebService1Soap = new QName("http://tempuri.org/", "WebService1Soap");
    public final static QName WebService1Soap12 = new QName("http://tempuri.org/", "WebService1Soap12");
    static {
        URL url = null;
        try {
            url = new URL("http://10.114.81.103:82/WebService1.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebService1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.114.81.103:82/WebService1.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebService1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebService1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebService1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebService1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebService1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap")
    public WebService1Soap getWebService1Soap() {
        return super.getPort(WebService1Soap, WebService1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap")
    public WebService1Soap getWebService1Soap(WebServiceFeature... features) {
        return super.getPort(WebService1Soap, WebService1Soap.class, features);
    }


    /**
     *
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap12")
    public WebService1Soap getWebService1Soap12() {
        return super.getPort(WebService1Soap12, WebService1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap12")
    public WebService1Soap getWebService1Soap12(WebServiceFeature... features) {
        return super.getPort(WebService1Soap12, WebService1Soap.class, features);
    }

}
