package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-28T15:39:48.209+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebService1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebService1Soap {

    @WebResult(name = "SendMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendMessage")
    @WebMethod(operationName = "SendMessage", action = "http://tempuri.org/SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendMessageResponse")
    public java.lang.String sendMessage(
        @WebParam(name = "strConnectorName", targetNamespace = "http://tempuri.org/")
        java.lang.String strConnectorName,
        @WebParam(name = "strDisServerHost", targetNamespace = "http://tempuri.org/")
        java.lang.String strDisServerHost,
        @WebParam(name = "strMessage", targetNamespace = "http://tempuri.org/")
        java.lang.String strMessage,
        @WebParam(name = "strMessageType", targetNamespace = "http://tempuri.org/")
        java.lang.String strMessageType,
        @WebParam(name = "strMessageSchema", targetNamespace = "http://tempuri.org/")
        java.lang.String strMessageSchema,
        @WebParam(name = "strNull", targetNamespace = "http://tempuri.org/")
        java.lang.String strNull
    );
}
